# Generated by Django 4.2.3 on 2023-07-04 00:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidadTI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID especialidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='soporteTI',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('especialidad', models.ManyToManyField(to='tickets.especialidadti', verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=500, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=100, verbose_name='descripcion')),
                ('soporte', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.soporteti', verbose_name='soporte')),
            ],
        ),
    ]
