# Generated by Django 4.2 on 2023-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="descripcion",
            field=models.TextField(verbose_name="descripcion"),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="titulo",
            field=models.CharField(max_length=500, verbose_name="Titulo"),
        ),
    ]
